[build]
  # Specify your build commands here
  # Example: installing dependencies
  commands = [
    "composer install"
  ]

[deploy]
  # Specify your deployment commands here
  # Example: running migrations, starting services
  commands = [
    "echo 'client_max_body_size 20M;' > /etc/nginx/conf.d/client_max_body_size.conf",
    "service nginx restart",  # Restart Nginx to apply the new configuration
    "php-fpm"  # Start PHP-FPM if needed
  ]
