<?php
include '../database/db_connection.php';

/* Activities:
activity_id (int) (PK) (AI)
activity_name (varchar(255))
category_id (int) (NULL) (FK=>category_id-->ActivityCategories::category_id)

ActivityCategories:
category_id (int) (PK) (AI)
category_name (varchar(255)) (NULL)

Countries:
country_id (int) (PK) (AI)
country_name (varchar(255))

EducationLevels:
education_level_id (int) (PK) (AI)
education_level_name (varchar(255))

GuideRequests:
request_id (int) (PK) (AI)
sender_id (int) (NULL) (FK=>sender_id-->Users::user_id)
receiver_id (int) (NULL) (FK=>receiver_id-->Users::user_id)
status (enum('pending','accepted','denied'))
request_timestamp (timestamp) (NULL)
response_timestamp (timestamp) (NULL)

Interests:
interest_id (int) (PK) (AI)
interest_name (varchar(255))

Languages:
language_id (int) (PK) (AI)
language_name (varchar(255))

Locations:
location_id (int) (PK) (AI)
location_name (varchar(255))
country_id (int) (NULL) (FK=>country_id-->Countries::country_id)

Messages:
message_id (int) (PK) (AI)
sender_id (int) (NULL) (FK=>sender_id-->Users::user_id)
receiver_id (int) (NULL) (FK=>receiver_id-->Users::user_id)
content (text)
timestamp (timestamp) (NULL)

PlacesToVisit:
place_id (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
location_id (int) (FK=>location_id-->Locations::location_id)

Professions:
profession_id (int) (PK) (AI)
profession_name (varchar(255))

RatingsAndReviews:
rating_id (int) (PK) (AI)
sender_id (int) (NULL) (FK=>sender_id-->Users::user_id)
receiver_id (int) (NULL) (FK=>receiver_id-->Users::user_id)
rating (int)
review_text (text) (NULL)
timestamp (timestamp) (NULL)

TravelDiary:
diary_id (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
title (varchar(255))
note (text) (NULL)
date_visited (date) (NULL)
visited_location_id (int) (NULL) (FK=>visited_location_id-->Locations::location_id)

TravelDiaryPhotos:
photo_id (int) (PK) (AI)
diary_id (int) (NULL) (FK=>diary_id-->TravelDiary::diary_id)
photo_path (varchar(255))

UserActivities:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
activity_id (int) (NULL) (FK=>activity_id-->Activities::activity_id)

UserCountries:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
country_id (int) (NULL) (FK=>country_id-->Countries::country_id)

UserEducationLevels:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
education_level_id (int) (NULL) (FK=>education_level_id-->EducationLevels::education_level_id)

UserInterests:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
interest_id (int) (NULL) (FK=>interest_id-->Interests::interest_id)

UserLanguages:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
language_id (int) (NULL) (FK=>language_id-->Languages::language_id)
language_level (int) (NULL)

UserLocations:
ID (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
location_id (int) (NULL) (FK=>location_id-->Locations::location_id)

UserLoginRecords:
record_id (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
login_timestamp (timestamp) (NULL)
logout_timestamp (timestamp) (NULL)
session_duration (int) (NULL)
login_status (tinyint(1))

UserProfessions:
ID (int) (PK) (AI)
user_id (int) (FK=>user_id-->Users::user_id)
profession_id (int) (FK=>profession_id-->Professions::profession_id)
years_of_experience (int) (NULL)

UserProfiles:
profile_id (int) (PK) (AI)
user_id (int) (NULL) (FK=>user_id-->Users::user_id)
name (varchar(255))
surname (varchar(255))
phone_number (varchar(255)) (NULL)
birth_date (date) (NULL)
tc_id (varchar(255)) (NULL)
thumbnail_text (text) (NULL)
profile_text (text) (NULL)
profile_picture_path (varchar(255)) (NULL)
algorithm_data_file_path (varchar(255)) (NULL)
has_car (tinyint(1)) (NULL)
has_house (tinyint(1)) (NULL)

UserRoles:
role_id (int) (PK) (AI)
role_name (varchar(255))

Users:
user_id (int) (PK) (AI)
username (varchar(255))
email (varchar(255))
password (varchar(255))
role_id (int) (NULL) (FK=>role_id-->UserRoles::role_id)
is_deleted (tinyint(1)) */

//$query = "ALTER TABLE Countries CHANGE COLUMN id country_id INT AUTO_INCREMENT;";

//$query = "ALTER TABLE Countries AUTO_INCREMENT = 1;";

//$query= "ALTER TABLE Locations ADD FOREIGN KEY (country_id) REFERENCES Countries(country_id);";

//$query = "SHOW CREATE TABLE Locations;";

// --Belirli bir tablo için foreign key adlarını sorgulama--
// --'tablo_adi' yerine, foreign key'leri öğrenmek istediğiniz tablonun adını girin.--
// $sql = "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'buddy_database' AND TABLE_NAME = 'UserCountries' AND CONSTRAINT_NAME <> 'PRIMARY'";

// $result = $conn->query($sql);

// if ($result->num_rows > 0) {
//   // Sonuçları döngü ile işleme
//   while($row = $result->fetch_assoc()) {
//     echo "Foreign key adı: " . $row["CONSTRAINT_NAME"]. "<br>";
//   }
// } else {
//   echo "Bu tabloda foreign key bulunamadı.";
// }

// --Belirli bir tablodaki foreign key'lerin nereden nereye bağlandığını sorgulama---
// --'veritabani_adi' ve 'tablo_adi' yerine kendi veritabanı ve tablo adınızı girin.--
// $sql = "SELECT 
//           kcu.CONSTRAINT_NAME, 
//           kcu.TABLE_NAME AS 'Foreign Table', 
//           kcu.COLUMN_NAME AS 'Foreign Column', 
//           kcu.REFERENCED_TABLE_NAME AS 'Referenced Table', 
//           kcu.REFERENCED_COLUMN_NAME AS 'Referenced Column' 
//         FROM 
//           INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
//         JOIN 
//           INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc 
//           ON kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA 
//           AND kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
//         WHERE 
//           kcu.TABLE_SCHEMA = 'buddy_database' AND 
//           kcu.TABLE_NAME = 'UserCountries'";

// $result = $conn->query($sql);

// if ($result->num_rows > 0) {
//   // Sonuçları döngü ile işleme
//   while($row = $result->fetch_assoc()) {
//     echo "Foreign Key: " . $row["CONSTRAINT_NAME"]. "<br>Foreign Table: " . $row["Foreign Table"]. "<br>Foreign Column: " . $row["Foreign Column"]. "<br>Referenced Table: " . $row["Referenced Table"]. "<br>Referenced Column: " . $row["Referenced Column"]. "<br><br>";
//   }
// } else {
//   echo "Bu tabloda foreign key bulunamadı.";
// }

//$query = "ALTER TABLE Locations DROP FOREIGN KEY Locations_ibfk_1";

// $query = "INSERT INTO Activities (activity_name, category_id) VALUES
// ('Ancient City Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Cultural Heritage')),
// ('Historical Site Exploration', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Cultural Heritage')),
// ('National Park Safari', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nature Exploration')),
// ('Mountain Trekking', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nature Exploration')),
// ('Local Cuisine Workshop', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Food and Drink')),
// ('Wine Tasting Event', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Food and Drink')),
// ('Ceramic Workshop', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Art and Crafts')),
// ('Street Art Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Art and Crafts')),
// ('Jazz Concert', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Music and Dance')),
// ('Folk Dance Performance', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Music and Dance')),
// ('Rooftop Bar Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nightlife')),
// ('Live Music Venues', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nightlife')),
// ('Old Market Shopping', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Shopping Paradise')),
// ('Boutique Shops Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Shopping Paradise')),
// ('Scuba Diving', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Water Sports')),
// ('Kite Surfing', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Water Sports')),
// ('Spa Day', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Health and Wellness')),
// ('Yoga Retreat', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Health and Wellness')),
// ('Golf Tournament', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Sports and Recreation')),
// ('Paintball', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Sports and Recreation')),
// ('Astronomy Observation', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Educational and Scientific')),
// ('Science Museum Visit', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Educational and Scientific')),
// ('Modern Art Museum', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Museums and Galleries')),
// ('History Museum Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Museums and Galleries')),
// ('Botanical Garden Visit', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Parks and Gardens')),
// ('City Park Picnic', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Parks and Gardens')),
// ('Iconic Buildings Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'City Tours')),
// ('Popular Neighborhoods Discovery', (SELECT category_id FROM ActivityCategories WHERE category_name = 'City Tours'));

// "

 /* $query = "INSERT INTO Interests (interest_name) VALUES
 ('Hiking'),
 ('Photography'),
 ('Cooking'),
 ('Sailing'),
 ('Diving'),
 ('History'),
 ('Art'),
 ('Music'),
 ('Wine Tasting'),
 ('Bird Watching'),
 ('Trekking'),
 ('Cycling'),
 ('Fishing'),
 ('Camping'),
 ('Mountaineering'),
 ('Skiing'),
 ('Surfing'),
 ('Nature Exploration'),
 ('Archaeology'),
 ('Astronomy'),
 ('Yoga'),
 ('Meditation'),
 ('Archery'),
 ('Horseback Riding'),
 ('Rock Climbing'),
 ('Snowboarding'),
 ('Jet Skiing'),
 ('Reading'),
 ('Theatre'),
 ('Cinema'),
 ('Dance'),
 ('Pottery'),
 ('Knitting'),
 ('Gaming'),
 ('Gardening'),
 ('Blogging'),
 ('Podcasting'),
 ('Volunteer Work'),
 ('DIY Projects'),
 ('Magic and Illusion');
 "; */

 /* $query = "INSERT INTO Languages (language_name) VALUES
 ('Turkish'),
 ('English'),
 ('Afar'),
 ('Abkhazian'),
 ('Afrikaans'),
 ('Amharic'),
 ('Arabic'),
 ('Assamese'),
 ('Aymara'),
 ('Azerbaijani'),
 ('Bashkir'),
 ('Belarusian'),
 ('Bulgarian'),
 ('Bihari'),
 ('Bislama'),
 ('Bengali/Bangla'),
 ('Tibetan'),
 ('Breton'),
 ('Catalan'),
 ('Corsican'),
 ('Czech'),
 ('Welsh'),
 ('Danish'),
 ('German'),
 ('Bhutani'),
 ('Greek'),
 ('Esperanto'),
 ('Spanish'),
 ('Estonian'),
 ('Basque'),
 ('Persian'),
 ('Finnish'),
 ('Fiji'),
 ('Faeroese'),
 ('French'),
 ('Frisian'),
 ('Irish'),
 ('Scots/Gaelic'),
 ('Galician'),
 ('Guarani'),
 ('Gujarati'),
 ('Hausa'),
 ('Hindi'),
 ('Croatian'),
 ('Hungarian'),
 ('Armenian'),
 ('Interlingua'),
 ('Interlingue'),
 ('Inupiak'),
 ('Indonesian'),
 ('Icelandic'),
 ('Italian'),
 ('Hebrew'),
 ('Japanese'),
 ('Yiddish'),
 ('Javanese'),
 ('Georgian'),
 ('Kazakh'),
 ('Greenlandic'),
 ('Cambodian'),
 ('Kannada'),
 ('Korean'),
 ('Kashmiri'),
 ('Kurdish'),
 ('Kirghiz'),
 ('Latin'),
 ('Lingala'),
 ('Laothian'),
 ('Lithuanian'),
 ('Latvian/Lettish'),
 ('Malagasy'),
 ('Maori'),
 ('Macedonian'),
 ('Malayalam'),
 ('Mongolian'),
 ('Moldavian'),
 ('Marathi'),
 ('Malay'),
 ('Maltese'),
 ('Burmese'),
 ('Nauru'),
 ('Nepali'),
 ('Dutch'),
 ('Norwegian'),
 ('Occitan'),
 ('(Afan)/Oromoor/Oriya'),
 ('Punjabi'),
 ('Polish'),
 ('Pashto/Pushto'),
 ('Portuguese'),
 ('Quechua'),
 ('Rhaeto-Romance'),
 ('Kirundi'),
 ('Romanian'),
 ('Russian'),
 ('Kinyarwanda'),
 ('Sanskrit'),
 ('Sindhi'),
 ('Sangro'),
 ('Serbo-Croatian'),
 ('Singhalese'),
 ('Slovak'),
 ('Slovenian'),
 ('Samoan'),
 ('Shona'),
 ('Somali'),
 ('Albanian'),
 ('Serbian'),
 ('Siswati'),
 ('Sesotho'),
 ('Sundanese'),
 ('Swedish'),
 ('Swahili'),
 ('Tamil'),
 ('Telugu'),
 ('Tajik'),
 ('Thai'),
 ('Tigrinya'),
 ('Turkmen'),
 ('Tagalog'),
 ('Setswana'),
 ('Tonga'),
 ('Tsonga'),
 ('Tatar'),
 ('Twi'),
 ('Ukrainian'),
 ('Urdu'),
 ('Uzbek'),
 ('Vietnamese'),
 ('Volapuk'),
 ('Wolof'),
 ('Xhosa'),
 ('Yoruba'),
 ('Chinese'),
 ('Zulu');
 "; */

//$query = "ALTER TABLE UserLanguages ADD COLUMN language_level INT;";

/* $query = "CREATE TABLE Professions (
    profession_id INT AUTO_INCREMENT PRIMARY KEY,
    profession_name VARCHAR(255) NOT NULL
  );
  "; */

/*  $query = "CREATE TABLE UserProfessions (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   user_id INT NOT NULL,
   profession_id INT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES Users(user_id),
   FOREIGN KEY (profession_id) REFERENCES Professions(profession_id)
 );"; */

//$query = "ALTER TABLE UserProfessions ADD COLUMN years_of_experience INT;";

/* $query = "INSERT INTO Professions (profession_name) VALUES 
('Occupations'),
('Accountant'),
('Accounts Assistant'),
('Accounts Clerk'),
('Accounts Manager'),
('Accounts Staff'),
('Acoustic Engineer'),
('Actor'),
('Actress'),
('Actuary'),
('Acupuncturist'),
('Adjustor'),
('Administration Assistant'),
('Administration Clerk'),
('Administration Manager'),
('Administration Staff'),
('Administrator'),
('Advertising Agent'),
('Advertising Assistant'),
('Advertising Clerk'),
('Advertising Contractor'),
('Advertising Executive'),
('Advertising Manager'),
('Advertising Staff'),
('Aerial Erector'),
('Aerobic Instructor'),
('Aeronautical Engineer'),
('Agent'),
('Air Traffic Controller'),
('Aircraft Designer'),
('Aircraft Engineer'),
('Aircraft Maintenance Engineer'),
('Aircraft Surface Finisher'),
('Airman'),
('Airport Controller'),
('Airport Manager'),
('Almoner'),
('Ambulance Controller'),
('Ambulance Crew'),
('Ambulance Driver'),
('Amusement Arcade Worker'),
('Anaesthetist'),
('Analyst'),
('Analytical Chemist'),
('Animal Breeder'),
('Anthropologist'),
('Antique Dealer'),
('Applications Engineer'),
('Applications Programmer'),
('Arbitrator'),
('Arborist'),
('Archaeologist'),
('Architect'),
('Archivist'),
('Area Manager'),
('Armourer'),
('Aromatherapist'),
('Art Critic'),
('Art Dealer'),
('Art Historian'),
('Art Restorer'),
('Artexer'),
('Artist'),
('Arts'),
('Assembly Worker'),
('Assessor'),
('Assistant'),
('Assistant Caretaker'),
('Assistant Cook'),
('Assistant Manager'),
('Assistant Nurse'),
('Assistant Teacher'),
('Astrologer'),
('Astronomer'),
('Attendant'),
('Au Pair'),
('Auction Worker'),
('Auctioneer'),
('Audiologist'),
('Audit Clerk'),
('Audit Manager'),
('Auditor'),
('Auto Electrician'),
('Auxiliary Nurse'),
('Bacon Curer'),
('Baggage Handler'),
('Bailiff'),
('Baker'),
('Bakery Assistant'),
('Bakery Manager'),
('Bakery Operator'),
('Balloonist'),
('Bank Clerk'),
('Bank Manager'),
('Bank Messenger'),
('Baptist Minister'),
('Bar Manager'),
('Bar Steward'),
('Barber'),
('Barmaid'),
('Barman'),
('Barrister'),
('Beautician'),
('Beauty Therapist'),
('Betting Shop'),
('Bill Poster'),
('Bingo Caller'),
('Biochemist'),
('Biologist'),
('Blacksmith'),
('Blind Assembler'),
('Blind Fitter'),
('Blinds Installer'),
('Boat Builder'),
('Body Fitter'),
('Bodyguard'),
('Bodyshop'),
('Book Binder'),
('Book Seller'),
('Book-Keeper'),
('Booking Agent'),
('Booking Clerk'),
('Bookmaker'),
('Botanist'),
('Branch Manager'),
('Breeder'),
('Brewer'),
('Brewery Manager'),
('Brewery Worker'),
('Bricklayer'),
('Broadcaster'),
('Builder'),
('Builders Labourer'),
('Building Advisor'),
('Building Control'),
('Building Engineer'),
('Building Estimator'),
('Building Foreman'),
('Building Inspector'),
('Building Manager'),
('Building Surveyor'),
('Bursar'),
('Bus Company'),
('Bus Conductor'),
('Bus Driver'),
('Bus Mechanic'),
('Bus Valeter'),
('Business Consultant'),
('Business Proprietor'),
('Butcher'),
('Butchery Manager'),
('Butler'),
('Buyer'),
('Cab Driver'),
('Cabinet Maker'),
('Cable Contractor'),
('Cable Jointer'),
('Cable TV Installer'),
('Cafe Owner'),
('Cafe Staff'),
('Cafe Worker'),
('Calibration Manager'),
('Camera Repairer'),
('Cameraman'),
('Car Dealer'),
('Car Delivery Driver'),
('Car Park Attendant'),
('Car Salesman'),
('Car Valet'),
('Car Wash Attendant'),
('Care Assistant'),
('Care Manager'),
('Careers Advisor'),
('Careers Officer'),
('Caretaker'),
('Cargo Operator'),
('Carpenter'),
('Carpet Cleaner'),
('Carpet Fitter'),
('Carpet Retailer'),
('Carphone Fitter'),
('Cartographer'),
('Cartoonist'),
('Cashier'),
('Casual Worker'),
('Caterer'),
('Catering Consultant'),
('Catering Manager'),
('Catering Staff'),
('Caulker'),
('Ceiling Contractor'),
('Ceiling Fixer'),
('Cellarman'),
('Chambermaid'),
('Chandler'),
('Chaplain'),
('Charge Hand'),
('Charity Worker'),
('Chartered'),
('Chartered Accountant'),
('Chauffeur'),
('Chef'),
('Chemist'),
('Chicken Chaser'),
('Child Minder'),
('Childminder'),
('Chimney Sweep'),
('China Restorer'),
('Chiropodist'),
('Chiropractor'),
('Choreographer'),
('Church Officer'),
('Church Warden'),
('Cinema Manager'),
('Circus Proprietor'),
('Circus Worker'),
('Civil Engineer'),
('Civil Servant'),
('Claims Adjustor'),
('Claims Assessor'),
('Claims Manager'),
('Clairvoyant'),
('Classroom Aide'),
('Cleaner'),
('Clergyman'),
('Cleric'),
('Clerk'),
('Commissioned'),
('Consultant'),
('Coroner'),
('Councillor'),
('Counsellor'),
('Dealer'),
('Decorator'),
('Delivery Driver'),
('Doctor'),
('Driver'),
('Economist'),
('Editor'),
('Employee'),
('Employment'),
('Engineer'),
('English Teacher'),
('Entertainer'),
('Envoy'),
('Executive'),
('Farmer'),
('Fireman'),
('Floor Layer'),
('Floor Manager'),
('Florist'),
('Flour Miller'),
('Flower Arranger'),
('Flying Instructor'),
('Foam Convertor'),
('Food Processor'),
('Footballer'),
('Foreman'),
('Forensic Scientist'),
('Forest Ranger'),
('Forester'),
('Fork Lift Truck Driver'),
('Forwarding Agent'),
('Foster Parent'),
('Foundry Worker'),
('Fraud Investigator'),
('French Polisher'),
('Fruiterer'),
('Fuel Merchant'),
('Fund Raiser'),
('Funeral Director'),
('Funeral Furnisher'),
('Furnace Man'),
('Furniture Dealer'),
('Furniture Remover'),
('Furniture Restorer'),
('Furrier'),
('Gallery Owner'),
('Gambler'),
('Gamekeeper'),
('Gaming Board Inspector'),
('Gaming Club Manager'),
('Gaming Club Proprietor'),
('Garage Attendant'),
('Garage Foreman'),
('Garage Manager'),
('Garda'),
('Garden Designer'),
('Gardener'),
('Gas Fitter'),
('Gas Mechanic'),
('Gas Technician'),
('Gate Keeper'),
('Genealogist'),
('General Practitioner'),
('Geologist'),
('Geophysicist'),
('Gilder'),
('Glass Worker'),
('Glazier'),
('Goldsmith'),
('Golf Caddy'),
('Golf Club Professional'),
('Golfer'),
('Goods Handler'),
('Governor'),
('Granite Technician'),
('Graphic Designer'),
('Graphologist'),
('Grave Digger'),
('Gravel Merchant'),
('Green Keeper'),
('Greengrocer'),
('Grocer'),
('Groom'),
('Ground Worker'),
('Groundsman'),
('Guest House Owner'),
('Guest House Proprietor'),
('Gun Smith'),
('Gynaecologist'),
('HGV Driver'),
('HGV Mechanic'),
('Hairdresser'),
('Handyman'),
('Hardware Dealer'),
('Haulage Contractor'),
('Hawker'),
('Health Advisor'),
('Health And Safety'),
('Health Care Assistant'),
('Health Consultant'),
('Health Nurse'),
('Health Planner'),
('Health Service'),
('Health Therapist'),
('Health Visitor'),
('Hearing Therapist'),
('Heating Engineer'),
('Herbalist'),
('Highway Inspector'),
('Hire Car Driver'),
('Historian'),
('History Teacher'),
('Hod Carrier'),
('Home Economist'),
('Home Help'),
('Homecare Manager'),
('Homeopath'),
('Homeworker'),
('Hop Merchant'),
('Horse Breeder'),
('Horse Dealer'),
('Horse Riding Instructor'),
('Horse Trader'),
('Horse Trainer'),
('Horticultural Consultant'),
('Horticulturalist'),
('Hosiery Mechanic'),
('Hosiery Worker'),
('Hospital Consultant'),
('Hospital Doctor'),
('Hospital Manager'),
('Hospital Orderly'),
('Hospital Technician'),
('Hospital Warden'),
('Hospital Worker'),
('Hostess'),
('Hot Foil Printer'),
('Hotel Consultant'),
('Hotel Worker'),
('Hotelier'),
('Househusband'),
('Housekeeper'),
('Housewife'),
('Housing Assistant'),
('Housing Officer'),
('Housing Supervisor'),
('Hygienist'),
('Hypnotherapist'),
('Hypnotist'),
('IT Consultant'),
('IT Manager'),
('IT Trainer'),
('Ice Cream Vendor'),
('Illustrator'),
('Immigration Officer'),
('Import Consultant'),
('Importer'),
('Independent Means'),
('Induction Moulder'),
('Industrial Chemist'),
('Industrial Consultant'),
('Injection Moulder'),
('Inspector'),
('Instructor'),
('Instrument Engineer'),
('Instrument Maker'),
('Instrument Supervisor'),
('Instrument Technician'),
('Insurance Agent'),
('Insurance Assessor'),
('Insurance Broker'),
('Insurance Consultant'),
('Insurance Inspector'),
('Insurance Staff'),
('Interior Decorator'),
('Interior Designer'),
('Interpreter'),
('Interviewer'),
('Inventor'),
('Investigator'),
('Investment Advisor'),
('Investment Banker'),
('Investment Manager'),
('Investment Strategist'),
('Ironmonger'),
('Janitor'),
('Jazz Composer'),
('Jeweller'),
('Jewellery'),
('Jockey'),
('Joiner'),
('Joinery Consultant'),
('Journalist'),
('Judge'),
('Keep Fit Instructor'),
('Kennel Hand'),
('Kitchen Worker'),
('Knitter'),
('Labelling Operator'),
('Laboratory Analyst'),
('Labourer'),
('Laminator'),
('Lampshade Maker'),
('Land Agent'),
('Land Surveyor'),
('Landlady'),
('Landlord'),
('Landowner'),
('Landworker'),
('Lathe Operator'),
('Laundry Staff'),
('Laundry Worker'),
('Lavatory Attendant'),
('Law Clerk'),
('Lawn Mower'),
('Lawyer'),
('Leaflet Distributor'),
('Leather Worker'),
('Lecturer'),
('Ledger Clerk'),
('Legal Advisor'),
('Legal Assistant'),
('Legal Executive'),
('Legal Secretary'),
('Letting Agent'),
('Liaison Officer'),
('Librarian'),
('Library Manager'),
('Licensed Premises'),
('Licensee'),
('Licensing'),
('Lifeguard'),
('Lift Attendant'),
('Lift Engineer'),
('Lighterman'),
('Lighthouse Keeper'),
('Lighting Designer'),
('Lighting Technician'),
('Lime Kiln Attendant'),
('Line Manager'),
('Line Worker'),
('Lineman'),
('Linguist'),
('Literary Agent'),
('Literary Editor'),
('Lithographer'),
('Litigation Manager'),
('Loans Manager'),
('Local Government'),
('Lock Keeper'),
('Locksmith'),
('Locum Pharmacist'),
('Log Merchant'),
('Lorry Driver'),
('Loss Adjustor'),
('Loss Assessor'),
('Lumberjack'),
('Machine Fitters'),
('Machine Minder'),
('Machine Operator'),
('Machine Setter'),
('Machine Tool'),
('Machine Tool Fitter'),
('Machinist'),
('Magician'),
('Magistrate'),
('Magistrates Clerk'),
('Maid'),
('Maintenance Fitter'),
('Make Up Artist'),
('Manicurist'),
('Manufacturing'),
('Map Mounter'),
('Marble Finisher'),
('Marble Mason'),
('Marine Broker'),
('Marine Consultant'),
('Marine Electrician'),
('Marine Engineer'),
('Marine Geologist'),
('Marine Pilot'),
('Marine Surveyor'),
('Market Gardener'),
('Market Research'),
('Market Researcher'),
('Market Trader'),
('Marketing Agent'),
('Marketing Assistant'),
('Marketing Coordinator'),
('Marketing Director'),
('Marketing Manager'),
('Marquee Erector'),
('Massage Therapist'),
('Masseur'),
('Masseuse'),
('Master Mariner'),
('Materials Controller'),
('Materials Manager'),
('Mathematician'),
('Maths Teacher'),
('Matron'),
('Mattress Maker'),
('Meat Inspector'),
('Meat Wholesaler'),
('Mechanic'),
('Medal Dealer'),
('Medical Advisor'),
('Medical Assistant'),
('Medical Consultant'),
('Medical Officer'),
('Medical Physicist'),
('Medical Practitioner'),
('Medical Researcher'),
('Medical Secretary'),
('Medical Student'),
('Medical Supplier'),
('Medical Technician'),
('Merchandiser'),
('Merchant'),
('Merchant Banker'),
('Merchant Seaman'),
('Messenger'),
('Metal Dealer'),
('Metal Engineer'),
('Metal Polisher'),
('Metal Worker'),
('Metallurgist'),
('Meteorologist'),
('Meter Reader'),
('Microbiologist'),
('Midwife'),
('Military Leader'),
('Milklady'),
('Milkman'),
('Mill Operator'),
('Mill Worker'),
('Miller'),
('Milliner'),
('Millwright'),
('Miner'),
('Mineralologist'),
('Minibus Driver'),
('Minicab Driver'),
('Mining Consultant'),
('Mining Engineer'),
('Money Broker'),
('Moneylender'),
('Mooring Contractor'),
('Mortgage Broker'),
('Mortician'),
('Motor Dealer'),
('Motor Engineer'),
('Motor Fitter'),
('Motor Mechanic'),
('Motor Racing'),
('Motor Trader'),
('Museum Assistant'),
('Museum Attendant'),
('Music Teacher'),
('Musician'),
('Nanny'),
('Navigator'),
('Negotiator'),
('Neurologist'),
('Newsagent'),
('Night Porter'),
('Night Watchman'),
('Nuclear Scientist'),
('Nun'),
('Nurse'),
('Nursery Assistant'),
('Nursery Nurse'),
('Nursery Worker'),
('Nurseryman'),
('Nursing Assistant'),
('Nursing Auxiliary'),
('Nursing Manager'),
('Nursing Sister'),
('Nutritionist'),
('Off Shore'),
('Office Manager'),
('Office Worker'),
('Oil Broker'),
('Oil Rig Crew'),
('Opera Singer'),
('Operations'),
('Operative'),
('Operator'),
('Optical'),
('Optical Advisor'),
('Optical Assistant'),
('Optician'),
('Optometrist'),
('Orchestral'),
('Organiser'),
('Organist'),
('Ornamental'),
('Ornithologist'),
('Orthopaedic'),
('Orthoptist'),
('Osteopath'),
('Outdoor Pursuits'),
('Outreach Worker'),
('Packaging'),
('Packer'),
('Paediatrician'),
('Paint Consultant'),
('Painter'),
('Palaeobotanist'),
('Palaeontologist'),
('Pallet Maker'),
('Panel Beater'),
('Paramedic'),
('Park Attendant'),
('Park Keeper'),
('Park Ranger'),
('Partition Erector'),
('Parts Man'),
('Parts Manager'),
('Parts Supervisor'),
('Party Planner'),
('Pasteuriser'),
('Pastry Chef'),
('Patent Agent'),
('Patent Attorney'),
('Pathologist'),
('Patrolman'),
('Pattern Cutter'),
('Pattern Maker'),
('Pattern Weaver'),
('Pawnbroker'),
('Payroll Assistant'),
('Payroll Clerk'),
('Payroll Manager'),
('Payroll Supervisor'),
('Personnel Officer'),
('Pest Controller'),
('Pet Minder'),
('Pharmacist'),
('Philatelist'),
('Photographer'),
('Physician'),
('Physicist'),
('Physiologist'),
('Physiotherapist'),
('Piano Teacher'),
('Piano Tuner'),
('Picture Editor'),
('Picture Framer'),
('Picture Reseacher'),
('Pig Man'),
('Pig Manager'),
('Pilot'),
('Pipe Fitter'),
('Pipe Inspector'),
('Pipe Insulator'),
('Pipe Layer'),
('Planning Engineer'),
('Planning Manager'),
('Planning Officer'),
('Planning Technician'),
('Plant Attendant'),
('Plant Driver'),
('Plant Engineer'),
('Plant Fitter'),
('Plant Manager'),
('Plant Operator'),
('Plasterer'),
('Plastics Consultant'),
('Plastics Engineer'),
('Plate Layer'),
('Plater'),
('Playgroup Assistant'),
('Playgroup Leader'),
('Plumber'),
('Podiatrist'),
('Police Officer'),
('Polisher'),
('Pool Attendant'),
('Pools Collector'),
('Porter'),
('Portfolio Manager'),
('Post Sorter'),
('Postman'),
('Postmaster'),
('Postwoman'),
('Potter'),
('Practice Manager'),
('Preacher'),
('Precision Engineer'),
('Premises'),
('Premises Security'),
('Press Officer'),
('Press Operator'),
('Press Setter'),
('Presser'),
('Priest'),
('Print Finisher'),
('Printer'),
('Prison Chaplain'),
('Prison Officer'),
('Private Investigator'),
('Probation Officer'),
('Probation Worker'),
('Procurator Fiscal'),
('Produce Supervisor'),
('Producer'),
('Product Installer'),
('Product Manager'),
('Production Engineer'),
('Production Hand'),
('Production Manager'),
('Production Planner'),
('Professional Boxer'),
('Professional Racing'),
('Professional Wrestler'),
('Progress Chaser'),
('Progress Clerk'),
('Project Co-ordinator'),
('Project Engineer'),
('Project Leader'),
('Project Manager'),
('Project Worker'),
('Projectionist'),
('Promoter'),
('Proof Reader'),
('Property Buyer'),
('Property Dealer'),
('Property Developer'),
('Property Manager'),
('Property Valuer'),
('Proprietor'),
('Psychiatrist'),
('Psychoanalyst'),
('Psychologist'),
('Psychotherapist'),
('Public House Manager'),
('Public Relations Of?cer'),
('Publican'),
('Publicity Manager'),
('Publisher'),
('Publishing Manager'),
('Purchase Clerk'),
('Purchase Ledger Clerk'),
('Purchasing Assistant'),
('Purchasing Manager'),
('Purser'),
('Quality Controller'),
('Quality Engineer'),
('Quality Inspector'),
('Quality Manager'),
('Quality Technician'),
('Quantity Surveyor'),
('Quarry Worker'),
('Racehorse Groom'),
('Racing Organiser'),
('Radio Controller'),
('Radio Director'),
('Radio Engineer'),
('Radio Operator'),
('Radio Presenter'),
('Radio Producer'),
('Radiographer'),
('Radiologist'),
('Rally Driver'),
('Receptionist'),
('Recorder'),
('Records Supervisor'),
('Recovery Vehicle Coordinator'),
('Recreational'),
('Recruitment Consultant'),
('Rector'),
('Reflexologist'),
('Refractory Engineer'),
('Refrigeration Engineer'),
('Refuse Collector'),
('Registrar'),
('Regulator'),
('Relocation Agent'),
('Remedial Therapist'),
('Rent Collector'),
('Rent Offcer'),
('Repair Man'),
('Repairer'),
('Reporter'),
('Representative'),
('Reprographic Assistant'),
('Research Analyst'),
('Research Consultant'),
('Research Director'),
('Research Scientist'),
('Research Technician'),
('Researcher'),
('Resin Caster'),
('Restaurant Manager'),
('Restaurateur'),
('Restorer'),
('Retired'),
('Revenue Clerk'),
('Revenue Officer'),
('Riding Instructor'),
('Rig Worker'),
('Rigger'),
('Riveter'),
('Road Safety Officer'),
('Road Sweeper'),
('Road Worker'),
('Roadworker'),
('Roof Tiler'),
('Roofer'),
('Rose Grower'),
('Royal Marine'),
('Rug Maker'),
('Saddler'),
('Safety Officer'),
('Sail Maker'),
('Sales Administrator'),
('Sales Assistant'),
('Sales Director'),
('Sales Engineer'),
('Sales Executive'),
('Sales Manager'),
('Sales Representative'),
('Sales Support'),
('Salesman'),
('Saleswoman'),
('Sand Blaster'),
('Saw Miller'),
('Scaffolder'),
('School Crossing'),
('School Inspector'),
('Scientific Officer'),
('Scientist'),
('Scrap Dealer'),
('Screen Printer'),
('Screen Writer'),
('Script Writer'),
('Sculptor'),
('Seaman'),
('Seamstress'),
('Secretary'),
('Security Consultant'),
('Security Controller'),
('Security Guard'),
('Security Officer'),
('Servant'),
('Service Engineer'),
('Service Manager'),
('Share Dealer'),
('Sheet Metal Worker'),
('Shelf Filler'),
('Shelter Warden'),
('Shepherd'),
('Sheriff'),
('Sheriff Clerk'),
('Sheriff Principal'),
('Shift Controller'),
('Ship Broker'),
('Ship Builder'),
('Shipping Clerk'),
('Shipping Officer'),
('Shipwright'),
('Shipyard Worker'),
('Shoe Maker'),
('Shoe Repairer'),
('Shooting Instructor'),
('Shop Assistant'),
('Shop Fitter'),
('Shop Keeper'),
('Shop Manager'),
('Shop Proprietor'),
('Shot Blaster'),
('Show Jumper'),
('Showman'),
('Shunter'),
('Sign Maker'),
('Signalman'),
('Signwriter'),
('Site Agent'),
('Site Engineer'),
('Skipper'),
('Slater'),
('Slaughterman'),
('Smallholder'),
('Social Worker'),
('Software Consultant'),
('Software Engineer'),
('Soldier'),
('Solicitor'),
('Song Writer'),
('Sound Artist'),
('Sound Engineer'),
('Sound Technician'),
('Special Constable'),
('Special Needs'),
('Speech Therapist'),
('Sports Administrator'),
('Sports Coach'),
('Sports Commentator'),
('Sportsman'),
('Sportsperson'),
('Sportswoman'),
('Spring Maker'),
('Stable Hand'),
('Staff Nurse'),
('Stage Director'),
('Stage Hand'),
('Stage Manager'),
('Stage Mover'),
('Station Manager'),
('Stationer'),
('Statistician'),
('Steel Erector'),
('Steel Worker'),
('Steeplejack'),
('Stenographer'),
('Steward'),
('Stewardess'),
('Stock Controller'),
('Stock Manager'),
('Stockbroker'),
('Stockman'),
('Stocktaker'),
('Stone Cutter'),
('Stone Sawyer'),
('Stonemason'),
('Store Detective'),
('Storeman'),
('Storewoman'),
('Street Entertainer'),
('Street Trader'),
('Stud Hand'),
('Student'),
('Student Nurse'),
('Student Teacher'),
('Studio Manager'),
('Sub-Postmaster'),
('Sub-Postmistress'),
('Supervisor'),
('Supply Teacher'),
('Surgeon'),
('Surveyor'),
('Systems Analyst'),
('Systems Engineer'),
('Systems Manager'),
('TV Editor'),
('Tachograph Analyst'),
('Tacker'),
('Tailor'),
('Tank Farm Operative'),
('Tanker Driver'),
('Tanner'),
('Tattooist'),
('Tax Advisor'),
('Tax Analyst'),
('Tax Assistant'),
('Tax Consultant'),
('Tax Inspector'),
('Tax Manager'),
('Tax Officer'),
('Taxi Controller'),
('Taxi Driver'),
('Taxidermist'),
('Tea Blender'),
('Tea Taster'),
('Teacher'),
('Teachers Assistant'),
('Technical Advisor'),
('Technical Analyst'),
('Technical Assistant'),
('Technical Author'),
('Technical Clerk'),
('Technical Co-ordinator'),
('Technical Director'),
('Technical Editor'),
('Technical Engineer'),
('Technical Illustrator'),
('Technical Instructor'),
('Technical Liaison'),
('Technical Manager'),
('Technician'),
('Telecommunication'),
('Telecommunications'),
('Telegraphist'),
('Telemarketeer'),
('Telephone Engineer'),
('Telephonist'),
('Telesales Person'),
('Television Director'),
('Television Engineer'),
('Television Presenter'),
('Television Producer'),
('Telex Operator'),
('Temperature Time'),
('Tennis Coach'),
('Textile Consultant'),
('Textile Engineer'),
('Textile Technician'),
('Textile Worker'),
('Thatcher'),
('Theatre Manager'),
('Theatre Technician'),
('Theatrical Agent'),
('Therapist'),
('Thermal Engineer'),
('Thermal Insulator'),
('Ticket Agent'),
('Ticket Inspector'),
('Tiler'),
('Timber Inspector'),
('Timber Worker'),
('Tobacconist'),
('Toll Collector'),
('Tool Maker'),
('Tour Agent'),
('Tour Guide'),
('Town Clerk'),
('Town Planner'),
('Toy Maker'),
('Toy Trader'),
('Track Worker'),
('Tractor Driver'),
('Tractor Mechanic'),
('Trade Mark Agent'),
('Trade Union Official'),
('Trading Standards'),
('Traffic Warden'),
('Train Driver'),
('Trainee Manager'),
('Training Advisor'),
('Training Assistant'),
('Training Co-ordinator'),
('Training Consultant'),
('Training Instructor'),
('Training Manager'),
('Training Officer'),
('Transcriber'),
('Translator'),
('Transport Clerk'),
('Transport Consultant'),
('Transport Controller'),
('Transport Engineer'),
('Transport Manager'),
('Transport Officer'),
('Transport Planner'),
('Travel Agent'),
('Travel Clerk'),
('Travel Consultant'),
('Travel Courier'),
('Travel Guide'),
('Travel Guide Writer'),
('Travel Representative'),
('Travelling Showman'),
('Treasurer'),
('Tree Feller'),
('Tree Surgeon'),
('Trichologist'),
('Trinity House Pilot'),
('Trout Farmer'),
('Tug Skipper'),
('Tunneller'),
('Turf Accountant'),
('Turkey Farmer'),
('Turner'),
('Tutor'),
('Typesetter'),
('Typewriter Engineer'),
('Typist'),
('Tyre Builder'),
('Tyre Fitter'),
('Tyre Inspector'),
('Tyre Technician'),
('Undertaker'),
('Underwriter'),
('Upholsterer'),
('Valuer'),
('Valve Technician'),
('Van Driver'),
('Vehicle Assessor'),
('Vehicle Body Worker'),
('Vehicle Engineer'),
('Vehicle Technician'),
('Ventriloquist'),
('Verger'),
('Veterinary Surgeon'),
('Vicar'),
('Video Artist'),
('Violin Maker'),
('Violinist'),
('Voluntary Worker'),
('Wages Clerk'),
('Waiter'),
('Waitress'),
('Warden'),
('Warehouse Manager'),
('Warehouseman'),
('Warehousewoman'),
('Watchmaker'),
('Weaver'),
('Weighbridge Clerk'),
('Weighbridge Operator'),
('Welder'),
('Welfare Assistant'),
('Welfare Officer'),
('Welfare Rights Officer'),
('Wheel Clamper'),
('Wholesale Newspaper'),
('Window Cleaner'),
('Window Dresser'),
('Windscreen Fitter'),
('Wine Merchant'),
('Wood Carver'),
('Wood Cutter'),
('Wood Worker'),
('Word Processing Operator'),
('Works Manager'),
('Writer'),
('Yacht Master'),
('Yard Manager'),
('Youth Hostel Warden'),
('Youth Worker'),
('Zoo Keeper'),
('Zoo Manager'),
('Zoologist');"; */

/* $query = "INSERT INTO EducationLevels (education_level_name) VALUES
('Primary School'),
('Middle School'),
('High School'),
('Associate Degree'),
('Bachelor’s Degree'),
('Master’s Degree'),
('Doctorate');
"; */

/* $query = "ALTER TABLE Activities ADD COLUMN category_id INT;
"; */

/* $query = "CREATE TABLE ActivityCategories (
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(255)
);
"; */

/* $query = "ALTER TABLE Activities
ADD FOREIGN KEY (category_id)
REFERENCES ActivityCategories(category_id);
"; */

/* $query = "INSERT INTO ActivityCategories (category_name) VALUES
('Cultural Heritage'),
('Nature Exploration'),
('Food and Drink'),
('Art and Crafts'),
('Music and Dance'),
('Nightlife'),
('Shopping Paradise'),
('Water Sports'),
('Health and Wellness'),
('Sports and Recreation'),
('Educational and Scientific'),
('Museums and Galleries'),
('Parks and Gardens'),
('City Tours');
"; */

/* $query = "INSERT INTO Activities (activity_name, category_id) VALUES
('Ancient City Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Cultural Heritage')),
('Historical Site Exploration', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Cultural Heritage')),
('National Park Safari', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nature Exploration')),
('Mountain Trekking', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nature Exploration')),
('Local Cuisine Workshop', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Food and Drink')),
('Wine Tasting Event', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Food and Drink')),
('Ceramic Workshop', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Art and Crafts')),
('Street Art Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Art and Crafts')),
('Jazz Concert', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Music and Dance')),
('Folk Dance Performance', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Music and Dance')),
('Rooftop Bar Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nightlife')),
('Live Music Venues', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Nightlife')),
('Old Market Shopping', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Shopping Paradise')),
('Boutique Shops Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Shopping Paradise')),
('Scuba Diving', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Water Sports')),
('Kite Surfing', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Water Sports')),
('Spa Day', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Health and Wellness')),
('Yoga Retreat', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Health and Wellness')),
('Golf Tournament', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Sports and Recreation')),
('Paintball', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Sports and Recreation')),
('Astronomy Observation', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Educational and Scientific')),
('Science Museum Visit', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Educational and Scientific')),
('Modern Art Museum', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Museums and Galleries')),
('History Museum Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Museums and Galleries')),
('Botanical Garden Visit', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Parks and Gardens')),
('City Park Picnic', (SELECT category_id FROM ActivityCategories WHERE category_name = 'Parks and Gardens')),
('Iconic Buildings Tour', (SELECT category_id FROM ActivityCategories WHERE category_name = 'City Tours')),
('Popular Neighborhoods Discovery', (SELECT category_id FROM ActivityCategories WHERE category_name = 'City Tours'));
"; */

//$query = "DELETE FROM Interests WHERE interest_id > 40;";

//$query = "ALTER TABLE UserProfiles DROP COLUMN profession;";

//$query = "ALTER TABLE PlacesToVisit DROP COLUMN place_name;";

//$query = "ALTER TABLE PlacesToVisit ADD COLUMN location_id INT NOT NULL;";

/* $query = "ALTER TABLE PlacesToVisit
ADD FOREIGN KEY (location_id)
REFERENCES Locations(location_id);
"; */

//$query = "ALTER TABLE TravelDiary ADD COLUMN visited_location_id INT;";

/* $query = "ALTER TABLE TravelDiary
ADD FOREIGN KEY (visited_location_id)
REFERENCES Locations(location_id);
"; */

//$query = "ALTER TABLE GuideRequests ADD COLUMN location_id INT;";

/* $query = "ALTER TABLE GuideRequests
ADD FOREIGN KEY (location_id)
REFERENCES Locations(location_id);
"; */

// SQL statement to query foreign key constraint names
/* $sql = "SELECT CONSTRAINT_NAME 
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
        WHERE TABLE_SCHEMA = ? 
          AND TABLE_NAME = ? 
          AND CONSTRAINT_TYPE = 'FOREIGN KEY'";

// Prepare the SQL statement
$stmt = $conn->prepare($sql);

// Check if the statement was prepared correctly
if ($stmt === false) {
    die("Failed to prepare the statement: " . $conn->error);
}

$dbname = 'buddy_database';
$tableName= 'GuideRequests';

// Bind parameters to the prepared statement
$stmt->bind_param('ss', $dbname, $tableName);

// Execute the prepared statement
$stmt->execute();

// Bind result variables
$stmt->bind_result($constraintName);

// Fetch values
$found = false;
while ($stmt->fetch()) {
    echo "Foreign Key Constraint Name: $constraintName\n";
    $found = true;
}

if (!$found) {
    echo "No foreign keys found for the table '$tableName'.";
}

// Close statement
$stmt->close(); */

/* $foreign_key_name = "GuideRequests_ibfk_4";

$tableName = "GuideRequests";

$query = "ALTER TABLE $tableName DROP FOREIGN KEY $foreign_key_name;"; */

$query = "SELECT concat('DROP TABLE IF EXISTS `', table_name, '`;')
FROM information_schema.tables
WHERE table_schema = 'railway';";

mysqli_query($conn, $query);

mysqli_close($conn);